---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/camel.svg"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "rest2soap"
    version: "1.0.0"
    group: "fis.demo"
  name: "rest2soap"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  - name: "netty"
    port: 10000
    protocol: "TCP"
    targetPort: 10000
  selector:
    project: "rest2soap"
    provider: "fabric8"
    group: "fis.demo"
